version: '2.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: confluent-771-zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - food-inspection-violation_food-inspection-violation_kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: confluent-771-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_FETCH_MAX_BYTES: 200000000
    depends_on:
      - zookeeper
    networks:
      - food-inspection-violation_food-inspection-violation_kafka_network
networks:
  food-inspection-violation_food-inspection-violation_kafka_network:
    driver: bridge
